.gitmodules
.vscodeignore
README.md
cdt-gdb.code-workspace
package-lock.json
package.json
webpack.config.js

We now expect the adapter to be checked otu somewhere and we load
in the webpack config from there and merge it with ours.
See the README file for details.

Remove submodule and adjust build system.

---

package.json

This will be passed to the adapter to set the location of the log file.

Add property  for logFile location for launch and attach.

---

package.json

For some reason, when running "yarn pack", the out directory is
excluded.  For Theia, we would like to create archives that we can
download and use, and it works better if the "out" directory containing
the compiled scripts is included.  I suppose it won't change anything
for when it is used as a VSCode extension.
Signed-off-by: Simon Marchi <simon.marchi@ericsson.com>

 Add cdt-gdb-adapter to bundledDependencies

---

package.json

Hardcoding a path to an executable living in `node_modules` can cause
issues depending on how the hoisting is done by the package manager
used.
In my case, I am using a `cdt-gdb-vscode` fork inside a mono-repo setup,
and the `vscode` package is hoisted at the mono-repo root `node_modules`,
not inside `cdt-gdb-vscode/node_modules`.
A better way to call the script is to let the node package resolution
system take care of it.
This is why this commit makes the "postinstall" command a javascript
script.
Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

Change "postinstall" command

---

package.json

Feature will only work on UNIX systems, and fallback to the default way
of starting the Debug Adapter if not supported.
Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>
---
Add new launch/attach configuration option.

Add configuration options to open a GDB console

---

package.json

This PR bumps the version of the plugin listed in the `package.json`. Doing so will allow recent code changes to be picked up and published by the script that publishes the plugin to the Open VSX registry.
@jonahgraham @paul-marechal
At the moment, this plugin is only made publicly available in a packaged form via the Open VSX registry. It is currently published as an 'unowned'. Longer term it may be desirable to establish ownership of the `eclipse-cdt` namespace and publish the plugin more proactively.
Signed-off-by: Colin Grant <colin.grant@ericsson.com>

Bump version to prompt Open VSX publishing

---

package.json
src/memory/client/MemoryBrowser.tsx
src/memory/server/MemoryServer.ts
yarn.lock

This PR is to bring all dependencies to the latest versions in one go. This was spurred because we were depending on older node-sass that does not build anymore with node-gyp on my Ubuntu machine.

Upgrade all dependencies to latest versions

---

src/memory/client/MemoryBrowser.tsx

Hi @jonahgraham ,
I think this is an issue with data in "Length" box of Memory Browser.
Currently, the size of memory to be viewed is the value of "Location" box (address) but not "Length" box.
Could you please help to check it?

fix issue in lengthReq

---

src/memory/server/MemoryServer.ts

Currently, Memory Browser tab can load data in the last tab if opening multiple tabs of its. (the other tab opened first is Empty). When the second tab is opened, the first tab is overwritten by the second. That makes the instance of the first tab lost. ->When user switches to the first tab and click "Go", Server can get memory data but the result response to Client is incorrect. Data cannot be sent to Client → Data in the first tab is empty.
=>So the solution is: Create a new object `vscode.WebviewPanel`  for each context call `openPanel` -> Can use multiple Memory Browser views.

Implement multiple memory browser webview

---

package.json

Provides front-end change for https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/issues/253

Add automaticallyKillServer to target launch settings

---

package.json
yarn.lock

Currently, VSCode version is 1.78.0.
We need to update to the latest version at cdt-gdb-vscode

Update VSCode version

---

package.json
yarn.lock

This pulls in the latest features, most significantly:
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/268
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/271
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/273
The UART feature pulls in the additions to yarn.lock for the UART dedendencies.

Update to latest cdt-gdb-adapter

---

package.json

This PR introduces a set of parameters that allow us to configure a serial line in the adapter to print UART output from on-board/emulation debug to the debug console. These parameters include the TCP port to hook onto (for emulation programs outputting UART output), or the serial port on the host machine to capture UART output from. For the serial line, we also configure the baud rate, stop bits, handshaking method, etc.
This PR has a sister PR, https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/271, in the CDT-GDB-Adapter repository.

Adding the ability to configure serial port output to the debug console

---

esbuild.js

The CDT GDB Adapter's [`install.js`](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/33b2f35173f67563ebb1d42a6cd4aaf7484cb90c/install.js#L5) only runs the native build if the platform is Linux. That means that in other cases, there will be no `pty.node` file created, and we should not try to include it any bundle generated on a different platform. Alternatively, we could modify the adapter to run the build on other platforms, even if it is not anticipated that the code will be used.
This allows the plugin to be built smoothly on platforms other than Linux.
CC: @asimgunes

Don't include pty.node unless on Linux

---

package.json
yarn.lock

Adds support for these features in the adapter:
- setting cwd for gdb
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/306
- better handling of complex variables:
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/304
- environment variables
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/303
And the new launch.json settings needed to enable the above.
Along with a variety of bug fixes in the adapter.

Update to adapter 0.0.30 (cwd, environment and complex vars)

---

.eslintignore
.gitignore
.prettierignore
.vscodeignore
esbuild.js
package.json
src/memory/client/MemoryBrowser.tsx
src/memory/client/tsconfig.json
tsconfig.json

This PR reduces the effects of #96 to the following:
- Replaces Webpack with ESBuild (but only use it on the webview code, as before #96)
- Move the output directory to `dist` rather than `out`. This is so that any adjustments made since #96 continue to apply. It would easy to move back to `out` if that is preferred.
In particular:
- We go back to relying on `vsce`'s resolution of runtime depndencies to keep all of the node modules that are relevant at runtime.
- We use `tsc` to transpile into the `dist` folder, with `.d.ts` files in the expected 1:1 relationship with transpiled `.js` files.
Functionally, bundling worked fine for three of the four things to which it was applied, the extension code: the webview code, and the CDT-GDB Adapter's `debugAdapter` entry point. It failed for …

Include serialport bindings in package

---

package.json
yarn.lock

Update to adapter 0.0.32 (bug fixes, stepping granularity)
Adds support for these features/bug fixes in the adapter:
- A fix the newline handling for the UART
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/318
- New feature of supporting stepping granularity
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/309

Prepare for v0.0.108

---

package.json
yarn.lock

Includes:
- Refactor code to allow web extension
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/328
- Improved handling of ContinuedEvent
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/335
- Ensure 'interrupt' and 'disconnect' signals are sent before '-gdb-exit'
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/338
- Add API to pause target and wait for debugger to be suspended
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/339

Update to adapter 1.0.1 (web extension support and other improvements)

---

package.json
yarn.lock

Includes:
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/343

Publish v1.0.2 - (fix performance problem on large arrays)

---

package.json
yarn.lock

Includes:
- Improving the DisassembleRequest logic
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/341

Update to adapter 1.0.3 (fix disassembly request)

---

package.json

This resolves build issue:
Error: Both a .vscodeignore file and a "files" property
in package.json were found. VSCE does not support combining
both strategies. Either remove the .vscodeignore file or the
"files" property in package.json.
Fixes #125

Remove "files" from package.json as it conflicts with ".vscodeignore"

---

.github/workflows/ci.yml
package.json
src/memory/client/MemoryBrowser.tsx
yarn.lock

Follow up to #130 , related to #119 :
This PR
* Updates Node to version 20 for CI. Required by latest `vsce` version, and unblocks version bumps for other dependencies.
* Fixes `lint` script which was broken due to missing dev dependency `eslint-config-prettier` to integrate `prettier` with `eslint`.
* Fixes two minor issues found by linter. Linter not activated in CI yet.
The CI build step should now complete.

Update to Node 20 and prettier fix

---

.github/workflows/ci.yml

Update all GH actions to latest versions.
Among others should fix CI failures due to v3 action deprecation warning (escalated to an error) which started showing today without change to CI files.
Failure: https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/actions/runs/12813335805/job/35727152816
Log snippet:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

Bump GH action versions to latest

---

CHANGELOG.md
CONTRIBUTING.md
DEVELOPMENT.md
README.md
package.json

Updates the README to add some documentation for end users.
This PR focuses on prerequisites and launch configuration settings.
It probably doesn't make sense to extensively document the Memory Browser window which to my understanding is planned to be removed in future when some integration issues with Memory Inspector in the cdt-gdb-adapter are solved.

Documentation Updates

---

CHANGELOG.md
CONTRIBUTING.md
DEVELOPMENT.md
README.md
package.json

Addresses #136 (see issue for rational why not updating more dependencies first).
Should be merged after #135.
**_Note that this contains some potentially controversial changes concerning the extension's name._**
Preparations for first release to both VS Code marketplace and Open VSX registry.
- Targets ~v1.1.0~ v2.0.0.
- Updates version in `CHANGELOG.md` and `package.json`.
- Adds some missing/useful fields to the extension manifest. This includes `displayName` which is shown on the marketplace and presumably Open VSX instead of `cdt-gdb-vscode`.
- Set `displayName` to "CDT GDB Debug Adapter Extension"
- Changed `description` to "CDT GDB debug adapter extension for Visual Studio Code" to better agree with VS Code [brand guidelines](https://code.visualstudio.com/brand).
- Updated …

v2.0.0 preparations

---

package.json
yarn.lock

Includes these changes from the adapter:
- Add supportsEvaluateForHovers
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/347
- Disassembly address handling improvement
- https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/348

Update to adapter v1.0.4

---

.github/workflows/ci.yml
CHANGELOG.md
package.json

Addresses #144  - fix to be confirmed
Remove ` --ignore-scripts` during `yarn install` in CI.
Required to build dependencies, in particular `nativebuild` script of `cdt-gdb-adapter`.

#144: CI - do not ignore scripts for yarn install

---

src/extension.ts

Hello,
I added a custom event for triggering a re-render of breakpoints in source code, because just sending a breakpoint event from the adapter to the extension was not enough
Please see
https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/368

Adding a custom event to trigger re-rendering of breakpoints in source code

---

src/extension.ts

The custom event that was created for the sake of toggling all breakpoints for rendering them is no longer needed
For more info, check out https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/issues/360

removed unneeded custom bp event

---

CHANGELOG.md
package.json

I added the language array for the package.json as it is needed for making the `Open Disassembly View` command visible in the context menu of the source window.
Please check this issue for reference 
https://github.com/microsoft/vscode/issues/165872

Adding language array for package.json

---

CHANGELOG.md
README.md
package.json
yarn.lock

* Bump release version to v2.1.0
* Added `portDetectionTimeout` docs (comes with cdt-gdb-adapter v1.1.0)
* Bump cdt-gdb-adapter to [v1.1.0](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/releases/tag/v1.1.0)

v2.1.0 Release Preparations

---

DEVELOPMENT.md

Documents how to make a release to drive https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/issues/379 to completion.

Finish up cdt-gdb-adapter #379: "Releasing" docs
